# Generated by Django 5.2.7 on 2025-10-22 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_full_domain', models.CharField(max_length=255)),
                ('internal_ip_range', models.CharField(blank=True, max_length=100, null=True)),
                ('aws_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(blank=True, max_length=100, null=True)),
                ('apk_file_s3_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RUNNING', 'Çalışıyor'), ('REPORTING', 'Rapor Oluşturuluyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata')], default='PENDING', max_length=10)),
                ('output_directory', models.CharField(blank=True, max_length=1024)),
                ('report_file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
